### ISSUE TITLE
Automatically choose between CNAME and ALIAS

### ISSUE THREAD

**Issue by jkarneges** [dnsimple/dnsimple-services#46]
In #42, it was mentioned that it will be possible in the future for the user to select an optional subdomain.

Once this feature is implemented, it would be cool if the service would automatically choose to use CNAME instead of ALIAS, if a subdomain is provided. Maybe the `type` could be specified as `CNAME|ALIAS` to request this automatic behavior.

**Comment by weppos** [comment]
Thanks for the feedback @jkarneges. I'm closing for now as it's not actionable in this repo. We'll let you know should the feature be available in the future.
