### ISSUE TITLE
S3 Website Endpoint Differences

### ISSUE THREAD

**Issue by dylanegan** [dnsimple/dnsimple-services#48]
After setting up an S3 website on a Frankfurt located bucket the other day I was unable to get it loading through our domain set up via DNSimple services. That was until I realised that the endpoint differs from what DNSimple provides. I thought maybe this would be a quick fix to the template, but that isn't the case.

It seems like AWS has decided that sticking to standards isn't quite a useful feature for a large platform. Therefore we have the issue of the endpoints being different depending on the region. From a quick test it seems like only `eu-central-1` and `ap-northeast-2` are affected, as per below.
- `imple.s3-website.ap-northeast-2.amazonaws.com`
- `imple.s3-website.eu-central-1.amazonaws.com*
- `imple.s3-website-us-east-1.amazonaws.com`

As you can note, the difference is between `s3-website` and the chosen region, preferring to use a `.` instead of a `-`.

Why this is the case I do not know, but I also no longer work for a company with sway at AWS so contacting them as my lowly self would probably yield little to no useful response. I'd be happy to provide a fix if there's something I'm missing (another repository?), but it seems like you need to add some conditionals on your end.

**Comment by weppos** [comment]
This is a [deja vu](https://github.com/publicsuffix/list/pull/134). I think we should try to ping AWS and determine whether they are moving towards `-` or `.` (or both).

Thanks for the report @dylanegan

**Comment by dylanegan** [comment]
@weppos no problem. Any luck from AWS? Or at least any reasoning from them?

**Comment by weppos** [comment]
I contacted Amazon, at the time being I don't think they will normalize them.
