### ISSUE TITLE
Conditional records

### ISSUE THREAD

**Issue by fvdm** [dnsimple/dnsimple-services#6]
It would be nice to have conditional records in the config.json. This way there is no need for almost duplicate services, like the two for Droplr in PR #5.

If a certain field is filled then use specific records, else use other specific records (domain/subdomain services). Records without a condition are always included.

``` js
"records": [
  {
    "condition": {"subdomain": "not empty"},
    "name": "{{subdomain}}",
    ...
  },
  {
    "condition": {"subdomain": "empty"},
    "name": "",
    ...
  },
  {
    "name": "",
    "type": "TXT",
    "content": "always used"
  }
]
```

_(sorry for the close/open..buttons..)_

**Comment by weppos** [comment]
Closing as not directly actionable in this repository. Belongs to our internal system.
