### ISSUE TITLE
Heroku DNS change

### ISSUE THREAD

**Issue by sbastn** [dnsimple/dnsimple-services#60]
Heroku have changed their DNS target in order to simplify a few redirection when switching over to SSL: https://devcenter.heroku.com/changelog-items/1060

Note however that the docs still seem to lag behind since there are plenty of references to "herokuapp.com"

**Comment by weppos** [comment]
See https://github.com/dnsimple/dnsimple-services/issues/75 https://github.com/dnsimple/dnsimple-services/pull/76 https://github.com/dnsimple/dnsimple-services/pull/77
