### ISSUE TITLE
Update Google Mail MX records

### ISSUE THREAD

**Issue by sbastn** [dnsimple/dnsimple-services#61]
A customer contacted us alerting of a change in MX records for the Google Suite. 
<img width="600" alt="screen shot 2017-03-11 at 11 47 07 am" src="https://cloud.githubusercontent.com/assets/80610/23822625/7b88d2d0-0650-11e7-85fe-5288a26ce377.png">

We currently have these: 
- aspmx.l.google.com
- alt1.aspmx.l.google.com
- alt2.aspmx.l.google.com
- alt3.aspmx.l.google.com
- alt4.aspmx.l.google.com

Note that this list is not incorrect, but if an outage occurs on the `aspmx.l.google.com` cluster, email would stop working. We should consider adding `xxx.googlemail.com.` as well.

**Comment by weppos** [comment]
@sbastn according to https://support.google.com/a/answer/33915?hl=en the records we have are correct.

Do you have a reference to where you took the previous screenshot?

![screenshot 2018-11-24 at 11 09 46](https://user-images.githubusercontent.com/5387/48966920-7b471d80-efd9-11e8-9ab1-364543b0fc04.png)

**Comment by sbastn** [comment]
Closing. We have the correct records.
