### ISSUE TITLE
Heroku DNS change

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-services#75]
https://devcenter.heroku.com/changelog-items/1488

> Currently, when adding a custom domain on Common Runtime, Heroku currently specifies a DNS target based on your domain name e.g. my-domain-name.herokudns.com. On October 16, 2018, Heroku will change to a randomly generated DNS target scheme, e.g. whispering-willow-5678.herokudns.com.
> 
> You should always use the DNS target provided by Heroku Dashboard or API for your DNS configuration. The change only applies to apps and domains on the Heroku Common Runtime and existing custom domains will not be affected.

**Comment by sbastn** [comment]
Our one-click service supports the scenario described above. Is there anything for us to do?
<img width="725" alt="screen shot 2018-10-31 at 9 01 38 am" src="https://user-images.githubusercontent.com/80610/47773845-a8125880-dceb-11e8-88c7-5c9aa4bb795c.png">

**Comment by weppos** [comment]
See https://github.com/dnsimple/dnsimple-services/pull/76 https://github.com/dnsimple/dnsimple-services/pull/77
