### ISSUE TITLE
Webflow IP addresses need to be updated to use ALIAS

### ISSUE THREAD

**Issue by martinisoft** [dnsimple/dnsimple-services#79]
Per some customer feedback, it appears we are not configuring the correct IP addresses for webflow and we could instead use ALIAS records to correctly point to their service. The support page linked to by @synthemesc does not contain any IP address information, but their support informs us that it would be easier to use ALIAS records.

**Comment by synthemesc** [comment]
I’m not sure what info I gave, I contributed that a loooong time ago.

**Comment by synthemesc** [comment]
I found the article, it’s moved — https://university.webflow.com/glossary/dns-records
