### ISSUE TITLE
Rename Heroku configuration

### ISSUE THREAD

**Issue by sbastn** [dnsimple/dnsimple-services#99]
We currently prompt for the following Heroku fields this way:
<img width="714" alt="Screen Shot 2020-05-14 at 12 10 51 PM" src="https://user-images.githubusercontent.com/80610/81922156-ffc99980-95db-11ea-9c30-82267969e8f2.png">

A customer wrote in saying that the field above didn't really match the Heroku terminology. We should use "DNS Target" instead:
<img width="878" alt="bastayadepicar · Settings | Heroku 2020-05-14 12-11-40" src="https://user-images.githubusercontent.com/80610/81922344-44edcb80-95dc-11ea-9d65-841927fe6fe1.png">

**Comment by dallasread** [comment]
Closed by #121
